#!/usr/bin/env python3
''' 
Author(s): Anthony
Created date: 11/20/21
Description: This file exists to cleanly call chkpy from the command line
without messing with parameters. This file calls main but is the entry point for the user
'''
import main
import sys

main.main(sys.argv[1:])

#main.main(sys.argv[1:], sys.argv[2:])

#another possibility we could do that would only grab the filename and the one argument, would need to edit how main handles these though
#main.main(sys.argv[1], sys.argv[2])
#or even just getting rid of the second argument and looping through the first one would work